[package]
name = "sultan_android"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
sultan_core = { path = "../sultan_core" }
sultan = { path = "../sultan" }
axum = "0.8"
jni = { version = "0.21", default-features = false }
tokio = { version = "1", features = ["full"] }
once_cell = "1"
android_logger = "0.14"
log = "0.4"
time = "0.3"
