use async_trait::async_trait;
use sea_orm::ConnectionTrait;

use crate::domain::{DomainResult, model::token::Token};

/// Repository trait for Token (refresh token) operations.
///
/// This trait defines the contract for managing refresh tokens in the system.
/// All methods accept `RepoCtx<impl ConnectionTrait>` to support both direct database
/// access and transactional operations.
///
/// # Note
///
/// Unlike most entities, tokens use physical deletion (not soft-delete) and
/// the ID is auto-generated by the database (auto-increment).
///
/// # Implementations
///
/// - SQLite: [`SqliteTokenRepository`](crate::storage::sqlite::token::SqliteTokenRepository)
///
/// # Example
///
/// ```rust,ignore
/// use sultan_core::storage::token_repo::{TokenRepository, RepoCtx};
/// use sultan_core::storage::sqlite::token::SqliteTokenRepository;
///
/// async fn example(db: &DatabaseConnection) -> DomainResult<()> {
///     let repo = SqliteTokenRepository::new();
///     let ctx = RepoCtx {
///         ctx: Context::new(),
///         db,
///     };
///     
///     // Save a new refresh token
///     let token = Token {
///         id: 0, // Will be auto-generated
///         user_id: 12345,
///         expired_at: chrono::Utc::now() + chrono::Duration::days(30),
///         token: "refresh_token_value".to_string(),
///     };
///     repo.save(&ctx, &token).await?;
///     
///     // Get the token by its value
///     let found = repo.get_by_token(&ctx, "refresh_token_value").await?;
///     
///     // Delete the token (logout)
///     if let Some(t) = found {
///         repo.delete(&ctx, t.id).await?;
///     }
///     
///     Ok(())
/// }
/// ```
#[async_trait]
pub trait TokenRepository: Send + Sync {
    /// Saves a new refresh token.
    ///
    /// The token ID is auto-generated by the database (auto-increment).
    /// The provided `token.id` value is ignored.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Repository context with database connection
    /// * `token` - Token data to save
    ///
    /// # Returns
    ///
    /// * `Ok(())` - Token saved successfully
    /// * `Err(Error)` - Database error (e.g., foreign key violation if user doesn't exist)
    async fn save(
        &self,
        ctx: &super::RepoCtx<impl ConnectionTrait>,
        token: &Token,
    ) -> DomainResult<()>;

    /// Physically deletes a refresh token.
    ///
    /// Unlike most entities, tokens are physically deleted (not soft-deleted).
    /// This is typically used for logout operations or token rotation.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Repository context with database connection
    /// * `id` - ID of the token to delete (database auto-generated ID)
    ///
    /// # Returns
    ///
    /// * `Ok(())` - Token deleted successfully
    /// * `Err(Error::NotFound)` - Token not found
    /// * `Err(Error)` - Database error
    async fn delete(&self, ctx: &super::RepoCtx<impl ConnectionTrait>, id: i64)
    -> DomainResult<()>;

    /// Retrieves a token by its token value.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Repository context with database connection
    /// * `token` - The refresh token string value
    ///
    /// # Returns
    ///
    /// * `Ok(Some(token))` - Token found
    /// * `Ok(None)` - Token not found
    /// * `Err(Error)` - Database error
    async fn get_by_token(
        &self,
        ctx: &super::RepoCtx<impl ConnectionTrait>,
        token: &str,
    ) -> DomainResult<Option<Token>>;
}
